<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbf7a12160731fe1a6f53b363417e9e30
{
    public static $files = array (
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
        '855b735dd4dacce159d965b6f270268a' => __DIR__ . '/..' . '/ryanwinchester/hubspot-php/src/helpers.php',
        '855b735dd4dacce159d965b6f270sdsd' => __DIR__ . '/..' . '/ryanwinchester/hubspot-php/src/Factory.php',
        '855b735dd4dacce159dafas3f270sdsd' => __DIR__ . '/..' . '/ryanwinchester/hubspot-php/src/Resources/Resource.php',
        '855b735dd4dacce159d9233df270sdsd' => __DIR__ . '/..' . '/ryanwinchester/hubspot-php/src/Resources/Contacts.php',
        '855b735dd4dacce159d9548as270sdsd' => __DIR__ . '/..' . '/ryanwinchester/hubspot-php/src/Resources/ContactLists.php',
        '855b735dd4dacce159d965b6f340sdsd' => __DIR__ . '/..' . '/ryanwinchester/hubspot-php/src/Http/Client.php',
        '855b735dd4dacce159d965b61223sdsd' => __DIR__ . '/..' . '/ryanwinchester/hubspot-php/src/Http/Response.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'MasterPopups\\SevenShores\\Hubspot\\' => 20,
        ),
        'P' => 
        array (
            'Psr\\Http\\Message\\' => 17,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MasterPopups\\SevenShores\\Hubspot\\' => 
        array (
            0 => __DIR__ . '/..' . '/ryanwinchester/hubspot-php/src',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbf7a12160731fe1a6f53b363417e9e30::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbf7a12160731fe1a6f53b363417e9e30::$prefixDirsPsr4;
        }, null, ClassLoader::class);
    }
}
